name: .NET Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - run: dotnet build -c Release
