name: .NET Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install wasm workload (macOS)
      if: matrix.os == 'macos-latest'
      run: sudo dotnet workload install wasm-tools

    - name: Install wasm workload (Windows/Linux)
      if: matrix.os != 'macos-latest'
      run: dotnet workload install wasm-tools

    - run: dotnet build -c Release

    - name: publish Web app
      run: dotnet publish Sentaur.Leaderboard.Web -c Release -o webapp

